<a href="https://colab.research.google.com/github/haleem-h/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  #numerical python-numpy

#array- collection of data with same data types(homogenous)

a=np.array([1,2,3.0,4])
print(a)

a=np.array([1,2,3.0,4,"a"])     #same data type- string
print(a)

[1. 2. 3. 4.]
['1' '2' '3.0' '4' 'a']


In [ ]:
#slicing- forward slicing, backward slicing


b=np.array([1,2,3,4,5])

#print 1,2
print(b[0:2])

#print 5,4
print(b[-1:-3:-1])

#print 4,5
print(b[3:5])

#print 2,1
print(b[-4::-1])

[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimension

a=np.array([0,2,3,4,5])
b=np.array([[1,2],[3,4]])

print(a.ndim)     #dimension=1vector
print(b.ndim)    #dimension=2 matrix

print(b)

print(b.shape)    #to know the shape- how many rows and columns 2x2

1
2
[[1 2]
 [3 4]]
(2, 2)


In [ ]:
#create a 2x2 matric 2,3,4,5


a=np.array([[2,3],[4,5]])

print(a)
print(a.shape)
print(a.ndim)

print(a.size)     #to get the no. of elements in a matrix

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 matrix nd print the matrix, size, shape


z=np.array([[1,2,3],[3,4,5]])

print(z)
print(z.size)
print(z.ndim)
print(z.shape)

[[1 2 3]
 [3 4 5]]
6
2
(2, 3)


In [ ]:
#create a 4x2 matrix display its size shape dimension

k=np.array([[1,2],[3,4],[5,6],[7,8]])

print(k)
print(k.size)
print(k.ndim)
print(k.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
8
2
(4, 2)


In [ ]:
#create a 4x4 matrix

x=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])

print(x)
print(x.shape)
print(x.ndim)
print(x.size)



[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
(4, 4)
2
16


In [ ]:
import numpy as np
x=np.array([[1,2,3,4],[2,5,2,2],[3,4,6,3],[4,5,6,4]])

print(x)            #in 4x4 matrix

print(x[0])
print(x[:,0])
print(x[1,1])
print(x[2,2])
print(x[3,2:])
print(x[0:3,1:])
print(x[0:,1])

[[1 2 3 4]
 [2 5 2 2]
 [3 4 6 3]
 [4 5 6 4]]
[1 2 3 4]
[1 2 3 4]
5
6
[6 4]
[[2 3 4]
 [5 2 2]
 [4 6 3]]
[2 5 4 5]


In [ ]:
#zero matrix

z=np.zeros([3,3,3])
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
z=np.zeros([3,3],dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
#one matrix

z=np.ones([3,3])    #float can be changed to int by adding ,dtype=int
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#create two 2x2 matrix

x=np.array([[1,1],[2,2]])
y=np.array([[3,3],[4,4]])
x
print(x.shape)
print(y.shape)

(2, 2)
(2, 2)


In [ ]:
#matrix addition

print(x+y)

#matrix substraction

print(x-y)

#matrix multiplication
print(x*y)  #not a matrix multiplication

print(x@y)        #matrix multipliction
print(x.dot(y))   #matrix multipliction

#matrix division

print(x/y)


#magic-  __add__:starts with underscores

[[4 4]
 [6 6]]
[[-2 -2]
 [-2 -2]]
[[3 3]
 [8 8]]
[[ 7  7]
 [14 14]]
[[ 7  7]
 [14 14]]
[[0.33333333 0.33333333]
 [0.5        0.5       ]]


In [ ]:
#full matrix- all elements are same

s=np.full([3,3],7,dtype=int)
s

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#create 3x4 matrix with value 9 and datatype complex

z=np.full([3,4],9,dtype=complex)
z

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#identity matrix

i=np.identity(3,dtype=int)
print(i)

z=np.eye(3)
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create 4x4 matrix

y=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
print(y.shape)
print(y)

print(y.size)


a=y.reshape(8,2)      #size will be fixed as 16
print(a)

(4, 4)
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
16
[[1 2]
 [3 4]
 [2 3]
 [4 5]
 [3 4]
 [5 6]
 [4 5]
 [6 7]]


In [ ]:
#arange

a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
#create a 5x2 matrix using arange

a=np.arange(1,11)
print(a)
r=a.reshape(5,2)
print(r)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
a=np.arange(1,11).reshape(5,2)
print(a)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#create 3x3 matrix with float values

a=np.array([[2.3,1.9,2.5],[2.5,5.6,7.5],[1.3,3.4,9.9]])
a

array([[2.3, 1.9, 2.5],
       [2.5, 5.6, 7.5],
       [1.3, 3.4, 9.9]])

In [ ]:
#floor

z=np.floor(a)
print(z)

[[2. 1. 2.]
 [2. 5. 7.]
 [1. 3. 9.]]


In [ ]:
#ceil

z=np.ceil(a)
z

array([[ 3.,  2.,  3.],
       [ 3.,  6.,  8.],
       [ 2.,  4., 10.]])

In [ ]:
#round

z=np.round(a)
z

array([[ 2.,  2.,  2.],
       [ 2.,  6.,  8.],
       [ 1.,  3., 10.]])

In [ ]:
#create 3x3 matrix

a=np.arange(1,10).reshape(3,3)
print(a)


print(a.max())
print(a.max(axis=1)) #max of each row
print(a.max(axis=0))  #max of each column

print(a.min())
print(a.min(axis=1))
print(a.min(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[3 6 9]
[7 8 9]
1
[1 4 7]
[1 2 3]


2

In [3]:
#flatten


import numpy as np

a=np.arange(1,10).reshape(3,3)
a.flatten()   #to convert into one dimensional array


#sorting

#create a3x3 matrix

a=np.array([1,2,3],[4,5,6],[7,8,9])
a.ndim
print(a)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given